/*
 * Workshop Computer USB Descriptors
 *
 * Copyright (c) 2026 MTM Workshop
 * Modified for Windows Compatibility (Split I/O Topology, No IAD)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

#include "bsp/board_api.h"
#include "tusb.h"
#include "usb_descriptors.h"

/* A combination of interfaces must have a unique product id, since PC will save device driver after the first plug.
 * Same VID/PID with different interface e.g MSC (first), then CDC (later) will possibly cause system error on PC.
 *
 * Auto ProductID layout's Bitmap:
 *   [MSB]     AUDIO | MIDI | HID | MSC | CDC          [LSB]
 */
#define PID_MAP(itf, n)  ((CFG_TUD_##itf) ? (1 << (n)) : 0)
#define USB_PID           (0x4049 | PID_MAP(CDC, 0) | PID_MAP(MSC, 1) | PID_MAP(HID, 2) | \
    PID_MAP(MIDI, 3) | PID_MAP(AUDIO, 4) | PID_MAP(VENDOR, 5) )

// Variables from main.cpp
extern uint8_t g_sampleRateIdx;
extern uint8_t g_channelsOut;
extern uint8_t g_channelsIn;
extern bool g_audioOnly;

//--------------------------------------------------------------------+
// Device Descriptors
//--------------------------------------------------------------------+
static tusb_desc_device_t desc_device =
{
    .bLength            = sizeof(tusb_desc_device_t),
    .bDescriptorType    = TUSB_DESC_DEVICE,
    .bcdUSB             = 0x0110,

    // Use Interface Association Descriptor (IAD) for Audio
    // As required by USB Specs IAD's subclass must be common class (2) and protocol must be IAD (1)
    .bDeviceClass       = 0x00,
    .bDeviceSubClass    = 0x00,
    .bDeviceProtocol    = 0x00,
    .bMaxPacketSize0    = CFG_TUD_ENDPOINT0_SIZE,

    .idVendor           = 0xCafe,
    .idProduct          = USB_PID,
    .bcdDevice          = 0x0100,

    .iManufacturer      = 0x01,
    .iProduct           = 0x02,
    .iSerialNumber      = 0x03,

    .bNumConfigurations = 0x01
};

// Invoked when received GET DEVICE DESCRIPTOR
// Application return pointer to descriptor
uint8_t const * tud_descriptor_device_cb(void)
{
  // Dynamic PID generation based on Config (Sample Rate + Channel Count)
  // Base: 0x4036
  // Variations: 3 Sample Rates * 9 Channel Combos (3 Out options * 3 In options) = 27 PIDs
  // Out/In Options: 2, 4, 6 -> Indices 0, 1, 2
  
  uint8_t out_idx = (g_channelsOut / 2) - 1;
  uint8_t in_idx  = (g_channelsIn / 2) - 1;
  if(out_idx > 2) out_idx = 2; // Safety
  if(in_idx > 2) in_idx = 2;   // Safety
  
  uint8_t combo_idx = (out_idx * 3) + in_idx;
  uint8_t config_offset = (g_sampleRateIdx * 9) + combo_idx;
  
  // Debug Mode: Add 0x100 to PID to force new driver installation
  uint16_t pid_base = USB_PID;
  if (g_audioOnly) pid_base += 0x0100;
  
  desc_device.idProduct = pid_base + config_offset;

  return (uint8_t const *)&desc_device;
}

//--------------------------------------------------------------------+
// Configuration Descriptor
//--------------------------------------------------------------------+
#define CONFIG_TOTAL_LEN    	(TUD_CONFIG_DESC_LEN + CFG_TUD_AUDIO * TUD_AUDIO_HEADSET_STEREO_DESC_LEN + CFG_TUD_MIDI * TUD_MIDI_DESC_LEN)

#if CFG_TUSB_MCU == OPT_MCU_LPC175X_6X || CFG_TUSB_MCU == OPT_MCU_LPC177X_8X || CFG_TUSB_MCU == OPT_MCU_LPC40XX
  // LPC 17xx and 40xx endpoint type (bulk/interrupt/iso) are fixed by its number
  // 0 control, 1 In, 2 Bulk, 3 Iso, 4 In etc ...
  #define EPNUM_AUDIO_IN    0x03
  #define EPNUM_AUDIO_OUT   0x03
  #define EPNUM_AUDIO_INT   0x01

#elif CFG_TUSB_MCU == OPT_MCU_CXD56
  // CXD56 USB driver has fixed endpoint type (bulk/interrupt/iso) and direction (IN/OUT) by its number
  // 0 control (IN/OUT), 1 Bulk (IN), 2 Bulk (OUT), 3 In (IN), 4 Bulk (IN), 5 Bulk (OUT), 6 In (IN)
  #define EPNUM_AUDIO_IN    0x01
  #define EPNUM_AUDIO_OUT   0x02
  #define EPNUM_AUDIO_INT   0x03

#elif CFG_TUSB_MCU == OPT_MCU_NRF5X
  // ISO endpoints for NRF5x are fixed to 0x08 (0x88)
  #define EPNUM_AUDIO_IN    0x08
  #define EPNUM_AUDIO_OUT   0x08
  #define EPNUM_AUDIO_INT   0x01

#elif defined(TUD_ENDPOINT_ONE_DIRECTION_ONLY)
  // MCUs that don't support a same endpoint number with different direction IN and OUT defined in tusb_mcu.h
  //    e.g EP1 OUT & EP1 IN cannot exist together
  #define EPNUM_AUDIO_IN    0x01
  #define EPNUM_AUDIO_OUT   0x02
  #define EPNUM_AUDIO_INT   0x03

#else
  #define EPNUM_AUDIO_IN    0x02
  #define EPNUM_AUDIO_OUT   0x01
  #define EPNUM_AUDIO_INT   0x04
  #define EPNUM_MIDI_IN     0x03
  #define EPNUM_MIDI_OUT    0x03
#endif

// UAC1: No IAD for MIDI (Simple interface)
#define CONFIG_UAC1_TOTAL_LEN    	(TUD_CONFIG_DESC_LEN + TUD_AUDIO10_HEADSET_STEREO_DESC_LEN(2) + TUD_MIDI_DESC_LEN)

// UAC1 Audio Only (Debug Mode) - No MIDI
#define CONFIG_UAC1_AUDIO_ONLY_LEN (TUD_CONFIG_DESC_LEN + TUD_AUDIO10_HEADSET_STEREO_DESC_LEN(2))

extern bool g_audioOnly;

// Helper macro to calculate endpoint size (Audio 1.0, 16-bit, +1 frame padding)
// Rate * Ch * 2bytes / 1000 + (Ch * 2bytes)
#define CALC_EP_SZ(_rate, _ch)   (TUD_AUDIO_EP_SIZE(false, _rate, 2, _ch) + ((_ch) * 4))

// ===== 48kHz Descriptors (3 Channel Count Variants) =====
// Standard (Composite)
uint8_t const desc_uac1_configuration_48k_6ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_6CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 6), \
      48000, 48000), // 6ch (3 stereo pairs)
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

uint8_t const desc_uac1_configuration_48k_4ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_4CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 4), \
      48000, 48000), // 4ch (2 stereo pairs)
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

uint8_t const desc_uac1_configuration_48k_2ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_2CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 2), \
      48000, 48000), // 2ch (1 stereo pair)
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 48kHz Asymmetric: 6 Out / 2 In (Idx 3)
uint8_t const desc_uac1_configuration_48k_6out_2in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 2), \
      48000, 48000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 48kHz Asymmetric: 2 Out / 6 In (Idx 4)
uint8_t const desc_uac1_configuration_48k_2out_6in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 6), \
      48000, 48000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 48kHz Asymmetric: 4 Out / 2 In
uint8_t const desc_uac1_configuration_48k_4out_2in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 2), \
      48000, 48000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 48kHz Asymmetric: 2 Out / 4 In
uint8_t const desc_uac1_configuration_48k_2out_4in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 4), \
      48000, 48000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 48kHz Asymmetric: 6 Out / 4 In
uint8_t const desc_uac1_configuration_48k_6out_4in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 4), \
      48000, 48000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 48kHz Asymmetric: 4 Out / 6 In
uint8_t const desc_uac1_configuration_48k_4out_6in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 6), \
      48000, 48000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// Audio Only (Debug Mode)
uint8_t const desc_uac1_configuration_48k_6ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_6CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 6), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_6out_2in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 2), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_2out_6in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 6), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_4out_2in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 2), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_2out_4in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 4), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_6out_4in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 4), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_4out_6in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 6), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_4ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_4CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 4), \
      48000, 48000)
};

uint8_t const desc_uac1_configuration_48k_2ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_2CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(48000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(48000, 2), \
      48000, 48000)
};

// ===== 44.1kHz Descriptors (3 Channel Count Variants) =====
// Standard (Composite)
uint8_t const desc_uac1_configuration_44k_6ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_6CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 6), \
      44100, 44100),
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

uint8_t const desc_uac1_configuration_44k_4ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_4CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 4), \
      44100, 44100),
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

uint8_t const desc_uac1_configuration_44k_2ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_2CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 2), \
      44100, 44100),
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 44.1kHz Asymmetric: 6 Out / 2 In (Idx 3)
uint8_t const desc_uac1_configuration_44k_6out_2in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 2), \
      44100, 44100), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 44.1kHz Asymmetric: 2 Out / 6 In (Idx 4)
uint8_t const desc_uac1_configuration_44k_2out_6in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 6), \
      44100, 44100), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 44.1kHz Asymmetric: 4 Out / 2 In
uint8_t const desc_uac1_configuration_44k_4out_2in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 2), \
      44100, 44100), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 44.1kHz Asymmetric: 2 Out / 4 In
uint8_t const desc_uac1_configuration_44k_2out_4in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 4), \
      44100, 44100), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 44.1kHz Asymmetric: 6 Out / 4 In
uint8_t const desc_uac1_configuration_44k_6out_4in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 4), \
      44100, 44100), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 44.1kHz Asymmetric: 4 Out / 6 In
uint8_t const desc_uac1_configuration_44k_4out_6in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 6), \
      44100, 44100), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// Audio Only (Debug Mode)
uint8_t const desc_uac1_configuration_44k_6ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_6CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 6), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_6out_2in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 2), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_2out_6in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 6), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_4out_2in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 2), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_2out_4in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 4), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_6out_4in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 4), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_4out_6in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 6), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_4ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_4CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 4), \
      44100, 44100)
};

uint8_t const desc_uac1_configuration_44k_2ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_2CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(44100, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(44100, 2), \
      44100, 44100)
};

// ===== 24kHz Descriptors (3 Channel Count Variants) =====
// Standard (Composite)
uint8_t const desc_uac1_configuration_24k_6ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_6CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 6), \
      24000, 24000),
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

uint8_t const desc_uac1_configuration_24k_4ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_4CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 4), \
      24000, 24000),
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

uint8_t const desc_uac1_configuration_24k_2ch[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_2CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 2), \
      24000, 24000),
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 24kHz Asymmetric: 6 Out / 2 In (Idx 3)
uint8_t const desc_uac1_configuration_24k_6out_2in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 2), \
      24000, 24000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 24kHz Asymmetric: 2 Out / 6 In (Idx 4)
uint8_t const desc_uac1_configuration_24k_2out_6in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 6), \
      24000, 24000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 24kHz Asymmetric: 4 Out / 2 In
uint8_t const desc_uac1_configuration_24k_4out_2in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 2), \
      24000, 24000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 24kHz Asymmetric: 2 Out / 4 In
uint8_t const desc_uac1_configuration_24k_2out_4in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 4), \
      24000, 24000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 24kHz Asymmetric: 6 Out / 4 In
uint8_t const desc_uac1_configuration_24k_6out_4in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 4), \
      24000, 24000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// 24kHz Asymmetric: 4 Out / 6 In
uint8_t const desc_uac1_configuration_24k_4out_6in[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC1_TOTAL_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 6), \
      24000, 24000), 
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

// Audio Only (Debug Mode)
uint8_t const desc_uac1_configuration_24k_6ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_6CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 6), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_6out_2in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 2), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_2out_6in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 6), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_4out_2in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 2, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 2), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_2out_4in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      2, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 4), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_6out_4in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      6, 4, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 6), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 4), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_4out_6in_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_ASYNC_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      4, 6, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 6), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_4ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_4CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 4), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 4), \
      24000, 24000)
};

uint8_t const desc_uac1_configuration_24k_2ch_audio_only[] =
{
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL-2, 0, CONFIG_UAC1_AUDIO_ONLY_LEN, 0x00, 100),
    TUD_AUDIO10_HEADSET_2CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX, \
      CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX, \
      EPNUM_AUDIO_OUT, CALC_EP_SZ(24000, 2), \
      EPNUM_AUDIO_IN | 0x80, CALC_EP_SZ(24000, 2), \
      24000, 24000)
};

// Verify all descriptor sizes match expected length
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_48k_6ch) == CONFIG_UAC1_TOTAL_LEN, "48k 6ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_48k_4ch) == CONFIG_UAC1_TOTAL_LEN, "48k 4ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_48k_2ch) == CONFIG_UAC1_TOTAL_LEN, "48k 2ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_44k_6ch) == CONFIG_UAC1_TOTAL_LEN, "44k 6ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_44k_4ch) == CONFIG_UAC1_TOTAL_LEN, "44k 4ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_44k_2ch) == CONFIG_UAC1_TOTAL_LEN, "44k 2ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_24k_6ch) == CONFIG_UAC1_TOTAL_LEN, "24k 6ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_24k_4ch) == CONFIG_UAC1_TOTAL_LEN, "24k 4ch size mismatch");
// TU_VERIFY_STATIC(sizeof(desc_uac1_configuration_24k_2ch) == CONFIG_UAC1_TOTAL_LEN, "24k 2ch size mismatch");

#if TUD_OPT_HIGH_SPEED

// UAC2: MIDI needs explicit IAD for Windows Composite handling
#define CONFIG_UAC2_TOTAL_LEN    	(TUD_CONFIG_DESC_LEN + TUD_AUDIO20_HEADSET_STEREO_DESC_LEN + TUD_MIDI_DESC_LEN + 8)

uint8_t const desc_uac2_configuration[] =
{
    // Config number, interface count, string index, total length, attribute, power in mA
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_UAC2_TOTAL_LEN, 0x00, 100),

    // String index, EP Out & EP In address, EP Interrupt address
    TUD_AUDIO20_HEADSET_STEREO_DESCRIPTOR(5, EPNUM_AUDIO_OUT, EPNUM_AUDIO_IN | 0x80, EPNUM_AUDIO_INT | 0x80),

    // MIDI IAD: Interface 3 (AC) & 4 (MS). Count 2. Class Audio (1), Subclass Control (1), Protocol 0.
    // Note: IAD must match the FIRST interface of the function (Audio Control)
    0x08, TUSB_DESC_INTERFACE_ASSOCIATION, ITF_NUM_MIDI, 2, TUSB_CLASS_AUDIO, AUDIO_SUBCLASS_CONTROL, 0x00, 0x00,

    // MIDI Descriptor
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 12, EPNUM_MIDI_OUT, (0x80 | EPNUM_MIDI_IN), 32)
};

TU_VERIFY_STATIC(sizeof(desc_uac2_configuration) == CONFIG_UAC2_TOTAL_LEN, "Incorrect size");


// device qualifier is mostly similar to device descriptor since we don't change configuration based on speed
tusb_desc_device_qualifier_t const desc_device_qualifier =
{
  .bLength            = sizeof(tusb_desc_device_qualifier_t),
  .bDescriptorType    = TUSB_DESC_DEVICE_QUALIFIER,
  .bcdUSB             = 0x0200,

  .bDeviceClass       = TUSB_CLASS_MISC,
  .bDeviceSubClass    = MISC_SUBCLASS_COMMON,
  .bDeviceProtocol    = MISC_PROTOCOL_IAD,

  .bMaxPacketSize0    = CFG_TUD_ENDPOINT0_SIZE,
  .bNumConfigurations = 0x01,
  .bReserved          = 0x00
};

// Invoked when received GET DEVICE QUALIFIER DESCRIPTOR request
// Application return pointer to descriptor, whose contents must exist long enough for transfer to complete.
// device_qualifier descriptor describes information about a high-speed capable device that would
// change if the device were operating at the other speed. If not highspeed capable stall this request.
uint8_t const *tud_descriptor_device_qualifier_cb(void)
{
  return (uint8_t const *) &desc_device_qualifier;
}

// Invoked when received GET OTHER SEED CONFIGURATION DESCRIPTOR request
// Application return pointer to descriptor, whose contents must exist long enough for transfer to complete
// Configuration descriptor in the other speed e.g if high speed then this is for full speed and vice versa
uint8_t const *tud_descriptor_other_speed_configuration_cb(uint8_t index)
{
  (void) index; // for multiple configurations

  // if link speed is high return fullspeed config, and vice versa
  return (tud_speed_get() == TUSB_SPEED_HIGH) ? desc_uac1_configuration_48k : desc_uac2_configuration;
}
#endif

// Invoked when received GET CONFIGURATION DESCRIPTOR
// Application return pointer to descriptor
// Descriptor contents must exist long enough for transfer to complete
// Invoked when received GET CONFIGURATION DESCRIPTOR
// Application return pointer to descriptor
// Descriptor contents must exist long enough for transfer to complete
uint8_t const * tud_descriptor_configuration_cb(uint8_t index)
{
  (void)index; // for multiple configurations

#if TUD_OPT_HIGH_SPEED
  // Use UAC2 descriptor for high speed
  return (tud_speed_get() == TUSB_SPEED_HIGH) ? desc_uac2_configuration : NULL;
#else
  // UAC1: Select descriptor based on sample rate, audio only flag, and channel counts
  // Matrix: [AudioOnly][Rate][Out][In]
  
  // 1. 48kHz
  if (g_sampleRateIdx == 0) {
      if (g_audioOnly) {
          if (g_channelsOut == 6) {
              if (g_channelsIn == 6) return desc_uac1_configuration_48k_6ch_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_48k_6out_4in_audio_only;
              if (g_channelsIn == 2) return desc_uac1_configuration_48k_6out_2in_audio_only;
          }
          else if (g_channelsOut == 4) {
              if (g_channelsIn == 6) return desc_uac1_configuration_48k_4out_6in_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_48k_4ch_audio_only;
              if (g_channelsIn == 2) return desc_uac1_configuration_48k_4out_2in_audio_only;
          }
          else { // Out == 2
              if (g_channelsIn == 6) return desc_uac1_configuration_48k_2out_6in_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_48k_2out_4in_audio_only;
              return desc_uac1_configuration_48k_2ch_audio_only;
          }
      } else {
          // Composite
          if (g_channelsOut == 6) {
              if (g_channelsIn == 6) return desc_uac1_configuration_48k_6ch;
              if (g_channelsIn == 4) return desc_uac1_configuration_48k_6out_4in;
              if (g_channelsIn == 2) return desc_uac1_configuration_48k_6out_2in;
          }
          else if (g_channelsOut == 4) {
              if (g_channelsIn == 6) return desc_uac1_configuration_48k_4out_6in;
              if (g_channelsIn == 4) return desc_uac1_configuration_48k_4ch;
              if (g_channelsIn == 2) return desc_uac1_configuration_48k_4out_2in;
          }
          else { // Out == 2
              if (g_channelsIn == 6) return desc_uac1_configuration_48k_2out_6in;
              if (g_channelsIn == 4) return desc_uac1_configuration_48k_2out_4in;
              return desc_uac1_configuration_48k_2ch;
          }
      }
  }
  
  // 2. 44.1kHz
  else if (g_sampleRateIdx == 1) {
      if (g_audioOnly) {
          if (g_channelsOut == 6) {
              if (g_channelsIn == 6) return desc_uac1_configuration_44k_6ch_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_44k_6out_4in_audio_only;
              if (g_channelsIn == 2) return desc_uac1_configuration_44k_6out_2in_audio_only;
          }
          else if (g_channelsOut == 4) {
              if (g_channelsIn == 6) return desc_uac1_configuration_44k_4out_6in_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_44k_4ch_audio_only;
              if (g_channelsIn == 2) return desc_uac1_configuration_44k_4out_2in_audio_only;
          }
          else { // Out == 2
              if (g_channelsIn == 6) return desc_uac1_configuration_44k_2out_6in_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_44k_2out_4in_audio_only;
              return desc_uac1_configuration_44k_2ch_audio_only;
          }
      } else {
          // Composite
          if (g_channelsOut == 6) {
              if (g_channelsIn == 6) return desc_uac1_configuration_44k_6ch;
              if (g_channelsIn == 4) return desc_uac1_configuration_44k_6out_4in;
              if (g_channelsIn == 2) return desc_uac1_configuration_44k_6out_2in;
          }
          else if (g_channelsOut == 4) {
              if (g_channelsIn == 6) return desc_uac1_configuration_44k_4out_6in;
              if (g_channelsIn == 4) return desc_uac1_configuration_44k_4ch;
              if (g_channelsIn == 2) return desc_uac1_configuration_44k_4out_2in;
          }
          else { // Out == 2
              if (g_channelsIn == 6) return desc_uac1_configuration_44k_2out_6in;
              if (g_channelsIn == 4) return desc_uac1_configuration_44k_2out_4in;
              return desc_uac1_configuration_44k_2ch;
          }
      }
  }
  
  // 3. 24kHz
  else {
      if (g_audioOnly) {
          if (g_channelsOut == 6) {
              if (g_channelsIn == 6) return desc_uac1_configuration_24k_6ch_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_24k_6out_4in_audio_only;
              if (g_channelsIn == 2) return desc_uac1_configuration_24k_6out_2in_audio_only;
          }
          else if (g_channelsOut == 4) {
              if (g_channelsIn == 6) return desc_uac1_configuration_24k_4out_6in_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_24k_4ch_audio_only;
              if (g_channelsIn == 2) return desc_uac1_configuration_24k_4out_2in_audio_only;
          }
          else { // Out == 2
              if (g_channelsIn == 6) return desc_uac1_configuration_24k_2out_6in_audio_only;
              if (g_channelsIn == 4) return desc_uac1_configuration_24k_2out_4in_audio_only;
              return desc_uac1_configuration_24k_2ch_audio_only;
          }
      } else {
          // Composite
          if (g_channelsOut == 6) {
              if (g_channelsIn == 6) return desc_uac1_configuration_24k_6ch;
              if (g_channelsIn == 4) return desc_uac1_configuration_24k_6out_4in;
              if (g_channelsIn == 2) return desc_uac1_configuration_24k_6out_2in;
          }
          else if (g_channelsOut == 4) {
              if (g_channelsIn == 6) return desc_uac1_configuration_24k_4out_6in;
              if (g_channelsIn == 4) return desc_uac1_configuration_24k_4ch;
              if (g_channelsIn == 2) return desc_uac1_configuration_24k_4out_2in;
          }
          else { // Out == 2
              if (g_channelsIn == 6) return desc_uac1_configuration_24k_2out_6in;
              if (g_channelsIn == 4) return desc_uac1_configuration_24k_2out_4in;
              return desc_uac1_configuration_24k_2ch;
          }
      }
  }
  
  return NULL; // Should not happen
#endif
}

//--------------------------------------------------------------------+
// String Descriptors
//--------------------------------------------------------------------+

// String Descriptor Index
enum {
  STRID_LANGID = 0,
  STRID_MANUFACTURER,
  STRID_PRODUCT,
  STRID_SERIAL,
};

// array of pointer to string descriptors
static char const *string_desc_arr[] =
{
  (const char[]) { 0x09, 0x04 },  // 0: is supported language is English (0x0409)
  "MTM Workshop",                 // 1: Manufacturer
  "Workshop Computer",            // 2: Product
  NULL,                           // 3: Serials will use unique ID if possible
  "Workshop Audio (UAC1)",        // 4: Function
  "Workshop Audio (UAC2)",        // 5: Function
  "Audio 1",                      // 6: Channel 1 Name
  "Audio 2",                      // 7: Channel 2 Name
  "CV 1",                         // 8: Channel 3 Name
  "CV 2",                         // 9: Channel 4 Name
  "Pulse 1",                      // 10: Channel 5 Name
  "Pulse 2",                      // 11: Channel 6 Name
  "Workshop MIDI",                // 12: MIDI Interface
};

static uint16_t _desc_str[32 + 1];

// Invoked when received GET STRING DESCRIPTOR request
// Application return pointer to descriptor, whose contents must exist long enough for transfer to complete
uint16_t const *tud_descriptor_string_cb(uint8_t index, uint16_t langid) {
  (void) langid;
  size_t chr_count;

  switch ( index ) {
    case STRID_LANGID:
      memcpy(&_desc_str[1], string_desc_arr[0], 2);
      chr_count = 1;
      break;

    case STRID_SERIAL:
      chr_count = board_usb_get_serial(_desc_str + 1, 32);
      break;

    default:
      // Note: the 0xEE index string is a Microsoft OS 1.0 Descriptors.
      // https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/microsoft-defined-usb-descriptors

      if ( !(index < sizeof(string_desc_arr) / sizeof(string_desc_arr[0])) ) return NULL;

      const char *str = string_desc_arr[index];

      // Cap at max char
      chr_count = strlen(str);
      size_t const max_count = sizeof(_desc_str) / sizeof(_desc_str[0]) - 1; // -1 for string type
      if ( chr_count > max_count ) chr_count = max_count;

      // Convert ASCII string into UTF-16
      for ( size_t i = 0; i < chr_count; i++ ) {
        _desc_str[1 + i] = str[i];
      }
      break;
  }

  // first byte is length (including header), second byte is string type
  _desc_str[0] = (uint16_t) ((TUSB_DESC_STRING << 8) | (2 * chr_count + 2));

  return _desc_str;
}
